main: de.raidcraft.rchome.RCHomePlugin
name: RCHome
version: ${project.version}#${build.number}
description: Provides player homes.
author: Strasse36
website: http://www.raid-craft.de
depend: [RaidCraft-API, WorldGuard]